export enum CommandEnum {
	NOOP = "",
	AHOJ = "AHOJ",
	SOUTH = "SOUTH",
	NORTH = "NORTH",
	WEST = "WEST",
	EAST = "EAST",
	JMENO = "JMENO",
	RESET = "RESET",
	SAVE = "SAVE",
	LOAD = "LOAD",
	LOOK = "LOOK",
	HELP = "HELP",
	TAKE = "TAKE",
}

export const commandAliases = {
	AHOJ: ["cau", "hi", "zdar", "cauko"],
	NORTH: ["n", "sever"],
	SOUTH: ["s", "jih"],
	EAST: ["e", "vychod"],
	JMENO: ["jmeno", "me jmeno", "jake je me jmeno"],
	RESET: ["reset"],
	SAVE: ["save"],
	LOAD: ["load"],
	LOOK: ["look", "podívej se", "kde jsem", "co to je", "x"],
	HELP: ["pomoc", "jak", "jak na to", "napoveda", "porad mi"],
	TAKE: ["vem", "vezmi", "seber", "zvedni", "get"],
	NOOP: [""],
};
