export enum CommandEnum {
	NOOP = "",
	AHOJ = "ahoj",
	SOUTH = "south",
	NORTH = "north",
	WEST = "west",
	EAST = "east",
	JMENO = "jmeno",
	RESET = "reset",
	SAVE = "save",
	LOAD = "load",
	LOOK = "look",
	HELP = "help",
	TAKE = "take",
}

export const commandAliases = {
	AHOJ: ["cau", "hi", "zdar", "cauko"],
	NORTH: ["n", "sever"],
	SOUTH: ["s", "jih"],
	EAST: ["e", "vychod"],
	JMENO: ["jmeno", "me jmeno", "jake je me jmeno"],
	RESET: ["reset"],
	SAVE: ["save"],
	LOAD: ["load"],
	LOOK: ["look", "podívej se", "kde jsem", "co to je", "x"],
	HELP: ["pomoc", "jak", "jak na to", "napoveda", "porad mi"],
	TAKE: ["vem", "vezmi", "seber", "zvedni", "get"],
	NOOP: [""],
};
