export enum LocationEnum {
	HOTEL_LOBBY = "HOTEL_LOBBY",
	HOTEL_STAIRCASE = "HOTEL_STAIRCASE",
	HOTEL_ROOM = "HOTEL_ROOM",
}

export enum LocationTypeEnum {
	PUBLIC = "PUBLIC",
	PRIVATE = "PRIVATE",
	HIDDEN = "HIDDEN",
}

export enum LocationDirectionEnum {
	NORTH = "NORTH",
	SOUTH = "SOUTH",
	EAST = "EAST",
	WEST = "WEST",
	UP = "UP",
	DOWN = "DOWN",
	LEFT = "LEFT",
	RIGHT = "RIGHT",
	FORWARD = "FORWARD",
	BACKWARD = "BACKWARD",
	NORTHEAST = "NORTHEAST",
	NORHWEST = "NORTHWEST",
	SOUTHEAST = "SOUTHEAST",
	SOUTHWEST = "SOUTHWEST",
}

export enum LocationStateEnum {
	NORMAL = "NORMAL",
	DISTORTED = "DISTORTED",
}
